security:
    providers:
        app_user_provider:
            memory:
                users:
                    admin:
                        password: 'password_hash_here'
                        roles: 'ROLE_ADMIN'
