version: '3.8'



services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: weather-php
        volumes:
            - ./:/var/www
        working_dir: /var/www
        depends_on:
            - db
        environment:
            DATABASE_URL: "pgsql://symfony:secret@db:5432/weather"

    nginx:
        image: nginx:latest
        container_name: weather-nginx
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: postgres:15
        container_name: weather-db
        restart: always
        environment:
            POSTGRES_DB: weather
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
