PHP_CONTAINER=weather-php

.PHONY: install run import-weather-data import-csv bash

install:
	composer install
	docker-compose up -d --build

run:
	docker exec -it $(PHP_CONTAINER) php bin/console doctrine:migrations:migrate --no-interaction && \
	docker exec -it $(PHP_CONTAINER) php bin/console app:download-csv
	docker exec -it $(PHP_CONTAINER) php bin/console app:import-csv

import-weather-data:
	docker exec -it $(PHP_CONTAINER) php bin/console app:download-csv

import-stations:
	docker exec -it $(PHP_CONTAINER) php bin/console app:import-csv

run_auto:
	docker exec -it weather-php php bin/console app:download-csv-auto


