parameters:
    stations_csv_path: '%kernel.project_dir%/var/data/stations.csv'

services:
    App\Command\:
        resource: '../src/Command'
        tags: [ 'console.command' ]
        autowire: true
        autoconfigure: true

    App\Security\ApiTokenAuthenticator:
        arguments:
            $validToken: '%env(API_SECRET)%'

    App\Controller\:
        resource: '../src/Controller'
        tags: [ 'controller.service_arguments' ]
        autowire: true
        autoconfigure: true

    App\Repository\:
        resource: '../src/Repository'
        autowire: true
        autoconfigure: true
        public: true

    App\Service\StationImporter:
        autowire: false
        autoconfigure: false
        public: true
        arguments:
            $csvPath: '%stations_csv_path%'
            $em: '@doctrine.orm.entity_manager'

    App\Service\CsvDownloader:
        arguments:
            $csvPath: '%stations_csv_path%'
        autowire: true
        autoconfigure: true
        public: true
